# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# 리뷰 언어 설정
# 선택지:
#   - "en-US" (기본값, 영어)
#   - "ko-KR" (한국어)
language: "ko-KR"  # 한국어로 리뷰 받기

# 얼리 액세스 기능 사용 여부 (베타 기능)
# 선택지: true / false
early_access: false  # 안정된 기능만 사용

reviews:
  # 리뷰 스타일(profile) 설정
  # 선택지:
  #   - "chill" (친근하고 부드러운 스타일)
  #   - "precise" (간결하고 직설적인 피드백)
  #   - "kind" (정중하고 따뜻한 스타일)
  #   - "nitpick" (작은 디테일까지 꼼꼼하게 짚는 스타일)
  profile: "nitpick"  # 간결하고 직설적인 피드백

  # 변경 요청 워크플로우 사용 여부 (GitHub에서 "Request changes" 포함 여부)
  # 선택지: true / false
  request_changes_workflow: true  # 리뷰만 하고, 변경 요청은 하지 않음

  # 리뷰 전체 요약 포함 여부
  # 선택지: true / false
  high_level_summary: true  # 리뷰 상단에 요약 제공

  # 시(詩) 형식의 요약 제공 여부
  # 선택지: true / false
  poem: false  # 재미 요소로 시 형식 요약 포함

  # 리뷰 상태 요약을 출력할지 여부 (승인 / 변경 요청 등 표시)
  # 선택지: true / false
  review_status: true  # 리뷰 상태를 명확하게 표시

  # walkthrough(코드 흐름 설명) 접기 여부
  # 선택지: true / false
  collapse_walkthrough: false  # 펼쳐서 보여주기

  auto_review:
    # PR 생성 시 자동 리뷰 수행 여부
    # 선택지: true / false
    enabled: true  # 자동으로 리뷰 시작

    # Draft PR에도 리뷰할지 여부
    # 선택지: true / false
    drafts: false  # Draft 상태 PR은 리뷰하지 않음

chat:
  # PR에서 질문이 달렸을 때 자동 응답 기능
  # 선택지: true / false
  auto_reply: true  # AI가 자동 응답해줌


# 🔧 선택적 설정 (원할 때 주석 해제해서 사용 가능)

suggestions:
  enabled: true         # AI가 코드 자동 수정 제안 (예: 코드 리팩토링)
  limit: 5              # 최대 제안 개수 설정 (기본값 3, 범위 1~5)

# code_context:
#   lines_before: 10      # 코드 리뷰 시 보여줄 이전 줄 수
#   lines_after: 10       # 코드 리뷰 시 보여줄 이후 줄 수

# github:
#   summarise_reviews: true  # GitHub PR 요약란에 리뷰 요약 포함

# allow_review_on_sensitive_files: false  # .env, .pem 같은 민감 파일 리뷰 금지

# max_review_size: 1000  # 리뷰 가능한 최대 줄 수 (초과 시 건너뜀)
